### ISSUE TITLE
ModuleNotFoundError: No module named 'models.tts'

### ISSUE THREAD

**Issue by xueqing0622** [807502278/ComfyUI_MaskGCT#6]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_MaskGCT\__init__.py", line 31, in <module>
    loadCustomNodes()# load Custom Nodes
    ^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_MaskGCT\__init__.py", line 21, in loadCustomNodes
    module = importlib.import_module(model_name, __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_MaskGCT\nodes\maskgct.py", line 14, in <module>
    from models.tts.maskgct.maskgct_utils import *
ModuleNotFoundError: No module named 'models.tts'

**Comment by 807502278** [comment]
Okay, I'll update it when I have time

**Comment by xueqing0622** [comment]
thx，have a  nice day

**Comment by leihaolei** [comment]
我怎么装也装不上

**Comment by 807502278** [comment]
Could you please provide the versions of Python, PyTorch, and the system, as well as the update date for ComfyUI?

**Comment by 807502278** [comment]
> 我怎么装也装不上

也是报这个错吗？方便提供下python，torch，系统版本，comfyui更新日期吗？

**Comment by xueqing0622** [comment]
Platform: Windows
** Python version: 3.11.9   
Total VRAM 12287 MB, total RAM 32671 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
Using xformers cross attention


win10 系统， comfyui 天天更新，已经0.30了。还是一样错误

**Comment by xlibfly** [comment]
我也是同样的问题

**Comment by 807502278** [comment]
I made some modifications to the import statements, and they work fine on my computer.
