### ISSUE TITLE
 (IMPORT FAILED): C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT

### ISSUE THREAD

**Issue by fandongminghitmt** [807502278/ComfyUI_MaskGCT#8]
1

2024-11-12 11:02:26,269 - root - INFO - Total VRAM 24564 MB, total RAM 130845 MB
2024-11-12 11:02:26,269 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-12 11:02:26,269 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 11:02:26,269 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 11:02:26,886 - root - INFO - Using pytorch cross attention
2024-11-12 11:02:27,580 - root - INFO - [Prompt Server] web root: C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
2024-11-12 11:02:27,581 - root - INFO - Adding extra search path checkpoints C:\Users\user\Documents\ComfyUI\models/checkpoints/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path classifiers C:\Users\user\Documents\ComfyUI\models/classifiers/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path clip C:\Users\user\Documents\ComfyUI\models/clip/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path clip_vision C:\Users\user\Documents\ComfyUI\models/clip_vision/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path configs C:\Users\user\Documents\ComfyUI\models/configs/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path controlnet C:\Users\user\Documents\ComfyUI\models/controlnet/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path diffusers C:\Users\user\Documents\ComfyUI\models/diffusers/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path diffusion_models C:\Users\user\Documents\ComfyUI\models/diffusion_models/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path embeddings C:\Users\user\Documents\ComfyUI\models/embeddings/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path gligen C:\Users\user\Documents\ComfyUI\models/gligen/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path hypernetworks C:\Users\user\Documents\ComfyUI\models/hypernetworks/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path loras C:\Users\user\Documents\ComfyUI\models/loras/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path photomaker C:\Users\user\Documents\ComfyUI\models/photomaker/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path style_models C:\Users\user\Documents\ComfyUI\models/style_models/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path unet C:\Users\user\Documents\ComfyUI\models/unet/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path upscale_models C:\Users\user\Documents\ComfyUI\models/upscale_models/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path vae C:\Users\user\Documents\ComfyUI\models/vae/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path vae_approx C:\Users\user\Documents\ComfyUI\models/vae_approx/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path animatediff_models C:\Users\user\Documents\ComfyUI\models/animatediff_models/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path animatediff_motion_lora C:\Users\user\Documents\ComfyUI\models/animatediff_motion_lora/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path animatediff_video_formats C:\Users\user\Documents\ComfyUI\models/animatediff_video_formats/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path ipadapter C:\Users\user\Documents\ComfyUI\models/ipadapter/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path liveportrait C:\Users\user\Documents\ComfyUI\models/liveportrait/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path insightface C:\Users\user\Documents\ComfyUI\models/insightface/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path layerstyle C:\Users\user\Documents\ComfyUI\models/layerstyle/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path LLM C:\Users\user\Documents\ComfyUI\models/LLM/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path Joy_caption C:\Users\user\Documents\ComfyUI\models/Joy_caption/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path sams C:\Users\user\Documents\ComfyUI\models/sams/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path blip C:\Users\user\Documents\ComfyUI\models/blip/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path CogVideo C:\Users\user\Documents\ComfyUI\models/CogVideo/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path xlabs C:\Users\user\Documents\ComfyUI\models/xlabs/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path instantid C:\Users\user\Documents\ComfyUI\models/instantid/
2024-11-12 11:02:27,582 - root - INFO - Adding extra search path custom_nodes C:\Users\user\Documents\ComfyUI\custom_nodes/
2024-11-12 11:02:27,909 - root - INFO - Total VRAM 24564 MB, total RAM 130845 MB
2024-11-12 11:02:27,909 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-12 11:02:27,909 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 11:02:27,909 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 11:02:28,763 - root - INFO - --------------
2024-11-12 11:02:28,763 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-12 11:02:28,768 - root - INFO - ChatGPT.available True
2024-11-12 11:02:28,769 - root - INFO - edit_mask.available True
2024-11-12 11:02:28,970 - root - INFO - ClipInterrogator.available True
2024-11-12 11:02:29,060 - root - INFO - PromptGenerate.available True
2024-11-12 11:02:29,060 - root - INFO - ChinesePrompt.available True
2024-11-12 11:02:29,060 - root - INFO - RembgNode_.available True
2024-11-12 11:02:29,338 - root - INFO - TripoSR.available
2024-11-12 11:02:29,339 - root - INFO - MiniCPMNode.available
2024-11-12 11:02:29,618 - root - INFO - Scenedetect.available
2024-11-12 11:02:29,665 - root - INFO - FishSpeech.available
2024-11-12 11:02:29,671 - root - INFO - SenseVoice.available
2024-11-12 11:02:29,695 - root - INFO - Whisper.available False
2024-11-12 11:02:29,701 - root - INFO - FalVideo.available
2024-11-12 11:02:29,701 - root - INFO - [93m -------------- [0m
2024-11-12 11:02:30,449 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\__init__.py", line 31, in <module>
    loadCustomNodes()# load Custom Nodes
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\__init__.py", line 21, in loadCustomNodes
    module = importlib.import_module(model_name, __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\ComfyUI\python\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\nodes\maskgct.py", line 14, in <module>
    from models.tts.maskgct.maskgct_utils import *
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\models\tts\maskgct\maskgct_utils.py", line 28, in <module>
    from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\models\tts\maskgct\g2p\g2p_generation.py", line 9, in <module>
    from models.tts.maskgct.g2p.g2p import PhonemeBpeTokenizer
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\models\tts\maskgct\g2p\g2p\__init__.py", line 6, in <module>
    from models.tts.maskgct.g2p.g2p import cleaners
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\models\tts\maskgct\g2p\g2p\cleaners.py", line 8, in <module>
    from models.tts.maskgct.g2p.g2p.mandarin import chinese_to_ipa
  File "C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT\models\tts\maskgct\g2p\g2p\mandarin.py", line 8, in <module>
    import jieba
  File "C:\Users\user\Documents\ComfyUI\python\Lib\site-packages\jieba\__init__.py", line 14, in <module>
    from . import finalseg
  File "C:\Users\user\Documents\ComfyUI\python\Lib\site-packages\jieba\finalseg\__init__.py", line 6, in <module>
    from .._compat import *
  File "C:\Users\user\Documents\ComfyUI\python\Lib\site-packages\jieba\_compat.py", line 18, in <module>
    import pkg_resources
  File "C:\Users\user\Documents\ComfyUI\python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

2024-11-12 11:02:30,449 - root - WARNING - Cannot import C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'
2024-11-12 11:02:31,321 - root - WARNING - Skip C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\DesktopSettingsExtension module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
2024-11-12 11:02:32,191 - root - INFO - 
Import times for custom nodes:
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds: C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\DesktopSettingsExtension
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-custom-scripts@1_0_0
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui_essentials@1_1_0
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-manager@3_0_0
2024-11-12 11:02:32,191 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI-MochiWrapper
2024-11-12 11:02:32,192 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/mikey_nodes@1_0_1
2024-11-12 11:02:32,192 - root - INFO -    0.0 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-kjnodes@1_0_1
2024-11-12 11:02:32,192 - root - INFO -    0.1 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-crystools@1_20_0
2024-11-12 11:02:32,192 - root - INFO -    0.2 seconds (IMPORT FAILED): C:\Users\user\Documents\ComfyUI\custom_nodes/ComfyUI_MaskGCT
2024-11-12 11:02:32,192 - root - INFO -    0.6 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-videohelpersuite@1_4_0
2024-11-12 11:02:32,192 - root - INFO -    0.9 seconds: C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-12 11:02:32,192 - root - INFO -    0.9 seconds: C:\Users\user\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\manager-core
2024-11-12 11:02:32,192 - root - INFO -    1.8 seconds: C:\Users\user\Documents\ComfyUI\custom_nodes/comfyui-mixlab-nodes@0_46_0
2024-11-12 11:02:32,192 - root - INFO - 
2024-11-12 11:02:32,199 - root - INFO - Setting output directory to: C:\Users\user\Documents\ComfyUI\output
2024-11-12 11:02:32,199 - root - INFO - Setting input directory to: C:\Users\user\Documents\ComfyUI\input
2024-11-12 11:02:32,199 - root - INFO - Setting user directory to: C:\Users\user\Documents\ComfyUI\user
2024-11-12 11:02:32,200 - root - INFO - Starting server

2024-11-12 11:02:32,200 - root - INFO - To see the GUI go to: http://127.0.0.1:8000

**Comment by fandongminghitmt** [comment]
No problem now
